source 'https://rubygems.org'
ruby '2.3.3'
gem 'sinatra'
gem 'data_mapper'
gem 'diffy'
gem 'sqlite3', :group => :development
gem 'dm-sqlite-adapter', :group => :development
gem 'pg', :group => :production